version: '2'
networks:
  wirdockenan.local:
    external: true
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
  # nur für Test zwecke
  # - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_PASSWORD=redis
    volumes:
      - ./data/Redis:/bitnami/redis/data
    networks:
      - wirdockenan.local