version: '2'
networks:
  bb2leer.local:
    external: true
services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
  # nur für Test zwecke
  # - ALLOW_EMPTY_PASSWORD=yes
  # - Redis Server Passwort kann hier geändert werden
    - REDIS_PASSWORD=redis
    volumes:
      - ./data/Redis:/bitnami/redis/data
    networks:
      - bb2leer.local