version: '3'
networks:
  wirdockenan.local:
    external: true
services:
  # Wird genutzt um beide MariaDB Datenbanken überschauen zu können.
  adminer:
    image: adminer
    restart: always
    networks:
      - wirdockenan.local
    ports:
      - 8008:8080