version: '3'
networks:
  wirdockenan.local:
    external: true
services:
  moodle:
    image: bitnami/moodle:4.3.2
    ports:
    # Benutze nur port 443  
    # - '82:8080'
      - '443:8443'
    environment:
    # Diesen Code nur Auskommentieren, wenn eine Moodle Datenbank schon existiert.
    # - MOODLE_SKIP_BOOTSTRAP
      - MOODLE_USERNAME=Admin
      - MOODLE_PASSWORD=Admin
      - MOODLE_SITE_NAME=WirDockenAn Moodle
      - MOODLE_DATABASE_HOST=mo-mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=MoUser
      - MOODLE_DATABASE_PASSWORD=MoUser
      - MOODLE_LANG=de
      - PHP_ENABLE_OPCACHE=true
      - PHP_MEMORY_LIMIT=512M
    volumes:
      - ./data/moodledata-data:/bitnami/moodledata
      - ./data/moodle_data:/bitnami/moodle
    # Falls man in der httpd.conf Code ändern möchte muss man ihm zuerst eine lokal bestehende datei mappen
    # - ./data/httpd/httpd.conf:/opt/bitnami/apache/conf/httpd.conf
    networks:
      - wirdockenan.local

  mo-mariadb:
    image: mariadb:11.2.2
    restart: always
    volumes:
      - ./data/mariadb-data:/var/lib/mariadb
      - ./data/mysql-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: Admin
      MARIADB_DATABASE: moodle
      MARIADB_USER: MoUser
      MARIADB_PASSWORD: MoUser
    networks:
      - wirdockenan.local
    ports:
      - 3306:3306