version: '3'
networks:
  bb2leer.local:
    external: true
services:
  phpldapadmin:
    # latest, da es seit 3 Jahren keine updates bekommt.
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    volumes:
      - ./data/phpldapadmin-data:/var/www/phpldapadmin
    ports:
      - "8080:80"
    networks:
      - bb2leer.local