version: '3'
networks:
  bb2leer.local:
    external: true
services:
  app:
    image: nextcloud:28.0
    restart: always
    container_name: Nextcloud
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE Nextcloud
      - MYSQL_USER NcUser
      - MYSQL_PASSWORD NcUser
      - MYSQL_HOST nc-mariaddb
      - NEXTCLOUD_MEMORY_LIMIT 2048M
      - REDIS_HOST=redis
    networks:
      - bb2leer.local
    ports:
      - "80:80"

  nc-mariadb:
    image: mariadb:11.2.2
    restart: always
    volumes:
      - ./data/mariadb-data:/var/lib/mariadb
      - ./data/mysql-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: Admin
      MARIADB_DATABASE: Nextcloud
    # Hier können die Login Daten der Nextcloud Datenbank geändert werden
      MARIADB_USER: NcUser
      MARIADB_PASSWORD: NcUser
      MYSQL_TCP_PORT: 3366
    networks:
      - bb2leer.local
    ports:
      - 3366:3306
    expose:
      - 3366