version: "3.7"
networks:
  WirDockenAn:
    external: true
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis-data:/data
    networks:
      - WirDockenAn
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=Admin
      - HTTP_PASSWORD=Admin
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - WirDockenAn
