version: '3'
networks:
  WirDockenAn:
    external: true
services:
  redis:
    image: redis:5.0-alpine
    volumes:
      - ./.data/redis:/data
    ports:
      - 6379:6379
    networks:
      - WirDockenAn

#  redis:
#    image: redis:7.2.3
#    restart: always
#    ports:
#      - 6379:6379
#    command: redis-server --save 20 1 --loglevel warning --requirepass redis
#  volumes: 
#      - ./data/redis:/data



#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    environment:
#      - REDIS_HOSTS=redis:6379
#      - HTTP_USER=Admin
#      - HTTP_PASSWORD=Admin
#    ports:
#      - 8081:8081
#    depends_on:
#      - redis
#    networks:
#      - WirDockenAn